# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d024b8776ddb42eef143f73f39db13a1cdf2d5d28ab39069409a29686515650ff8e6b1bf61f7bbcc254bfc4336d4fef7083dde00b5b9aeaee04b62cc4103434

test:
  secret_key_base: 5f1896f822651c46890ffb259f0882ebed431f5ec805a3c6a1401fb471754559e03baff421bd2da1ae1d01678080e778d52e2397e74e15d6b1732f3fbdab4b8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
